name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{https://gist.github.com/hiwon-lee/07c34eda00c8faf5ee6e2616a3f2dafc}}
          TIMEZONE: Asia/Taipei
